### ISSUE TITLE
Missing requirements

### ISSUE THREAD

**Issue by goanpeca** [rdemets/napari-yolov5#3]
Hi @rdemets 

It seems the [setup.cfg](https://github.com/rdemets/napari-yolov5/blob/main/setup.cfg#L35) file is missing some explicitly used packages 

```
flask
qtpy
scikit-image
tensorflow
wandb
```

Also it helps if dependencies are listed alphabetically :) 

Cheers!

**Comment by rdemets** [comment]
Good idea. Thanks for the suggestions. I just released a new version with the proper setup.cfg file.
